name=IDS Induction
version=1.0
author=Nils Hoppe
maintainer=Nils Hoppe
sentence=IDS induction plate library
paragraph=Library to control GGM Gastro ID1 and 2 induction plates
category=Signal Input/Output
url=https://github.com/nhhop/IdsInductionCooker
architectures=*
